config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
    path('polls/', include('polls.urls')),
    path('news/', include('news.urls')),
]

admin.site.site_header = "DevTory Admin"
admin.site.site_title = "DevTory Admin"
admin.site.index_title = "Welcome to DevTory Admin"

mysite/urls.py
from django.urls import path

from mysite import views

urlpatterns = [
    path('', views.index),
]

news/urls.py
from django.urls import path

from news import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:year>/', views.year_archive, name='year_list'),
    path('<int:year>/<int:month>', views.month_archive, name='month_list'),
    path('<int:pk>/detail/', views.detail, name='detail'),
]

polls/urls.py
from django.urls import path

from polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models


class Reporter(models.Model):
    full_name = models.CharField(max_length=70)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = '작성자목록'
        verbose_name_plural = '작성자목록'


class Article(models.Model):
    pub_date = models.DateTimeField(verbose_name='작성일시')
    headline = models.CharField(max_length=200, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE, verbose_name='작성자명')

    def __str__(self):
        return self.headline

    class Meta:
        verbose_name = '기사목록'
        verbose_name_plural = '기사목록'
        ordering = ('-pub_date', '-pk')

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    class Meta:
        db_table = 'TB_QUESTION'
        verbose_name = '질문목록'
        verbose_name_plural = '질문목록'

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        db_table = 'TB_QUESTION_CHOICE'
        verbose_name = '선택목록'
        verbose_name_plural = '선택목록'

    def __str__(self):
        return self.choice_text

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return HttpResponse("mysite index")

news/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from news.models import Article


def index(request):
    year = '2020'
    messages = {
        '<a href="{}">{}년 게시물 보기</a><br><br>'.format(year, year),
        '<a href="{}/{}">{}년 11월 게시물 보기</a><br><br>'.format(year, 11, year),
        '<a href="{}/{}">{}년 10월 게시물 보기</a><br><br>'.format(year, 10, year),
    }
    return HttpResponse(messages)


def year_archive(request, year):
    year_list = Article.objects.filter(pub_date__year=year)
    context = {'year': year, 'article_year_list': year_list}
    return render(request, 'news/index.html', context)


def month_archive(request, year, month):
    month_list = Article.objects.filter(pub_date__year=year, pub_date__month=month)
    context = {'year': year, 'month': month, 'article_month_list': month_list}
    return render(request, 'news/list_month.html', context)


def detail(request, pk):
    t_article = get_object_or_404(Article, id=pk)
    context = {'article': t_article}
    return render(request, 'news/detail.html', context)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

templates/news/base.html
{% load static %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <a href="{% url 'news:index' %}"><img src="{% static '/images/logo.png' %}" alt="Logo"></a>
    {% block content %}{% endblock %}
</body>
</html>

templates/news/detail.html
{% extends "news/base.html" %}

{% block title %}pk : {{ article.id }}{% endblock title %}

{% block content %}
    <h1>번호 : {{ article.id }}</h1>
    <hr>
    <p>HeadLine : {{ article.headline }}</p>
    <p>By : {{ article.reporter.full_name }}</p>
    <p>Published : {{ article.pub_date|date:"F j, Y" }}</p>
    <p>Contents : {{ article.content }}</p>
<a href="{% url 'news:index' %}">목록으로</a>
{% endblock content %}

templates/news/index.html
{% extends "news/base.html" %}

{% block title %}Articles for {{ year }}{% endblock title %}

{% block content %}
<h1>Articles for {{ year }}</h1>
<ul>
{% for article in article_year_list %}
    <li>
        <a href="{% url 'news:detail' article.id %}">{{ article.id }} | {{ article.headline }} | By {{ article.reporter.full_name }} | Published {{ article.pub_date|date:"F j, Y" }}</a>
    </li>
{% endfor %}
</ul>
<a href="{% url 'news:index' %}">메인으로</a>
{% endblock content %}

templates/news/list_month.html
{% extends "news/base.html" %}

{% block title %}Articles for {{ year }}/{{ month }}{% endblock title %}

{% block content %}
<h1>Articles for {{ year }}/{{ month }}</h1>
<ul>
{% for article in article_month_list %}
    <li>
        <a href="{% url 'news:detail' article.id %}">{{ article.id }} | {{ article.headline }} | By {{ article.reporter.full_name }} | Published {{ article.pub_date|date:"F j, Y" }}</a>
    </li>
{% endfor %}
</ul>
<a href="{% url 'news:index' %}">메인으로</a>
{% endblock content %}

templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>